server:
  port: 8081
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/quartz
    username: root
    password:
  redis:
    # 这里连接的是test03, 公网访问：47.93.157.59，内网访问：10.30.139.235
    host: 47.93.157.59
    port: 2333
    password: xtaaG9NfWEga
    jedis:
      pool:
        max-active: 10
        max-total: 20
        max-idle: 8
        min-idle: 0
        max-wait: 1000
        test-on-borrow: false








