server:
  port: 8081
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/quartz
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-total: 20
        max-idle: 8
        min-idle: 0
        max-wait: 1000
        test-on-borrow: false
  profiles:
    active: test

# 配置中心
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: b54efd5d-b36d-4906-bf51-03b842ff68d6







